#!/bin/bash -e

# Activate virtualenv Python environment
. /srv/cms/env_cms/bin/activate

# Dump database
cd /srv/cms/mainpage/mainpage
python manage.py dumpcms --settings=mainpage.settings_production > /srv/www/bindist/data/dumpcms.yaml
bzip2 -f /srv/www/bindist/data/dumpcms.yaml
